export const state = {
  config: null,
  roster: new Map(),
  activeSession: null,
  scanner: null,
  scanning: false,
  resumeScanOnShow: false,
  syncing: false,
  syncFailed: false,
  pending: 0,
  lastKey: '',
  lastTime: 0,
  flashTimer: null,
  wakeLock: null,
  audioCtx: null,
};
